version: '3'

services:
    golang:
        build:
            context: .
            dockerfile: docker/golang/Dockerfile
        tty: true
        ports:
            - "8080:8080"
        container_name: golang-server
        volumes:
            - ./go:/app
        environment:
            - "GOPATH:/go"
        command: /bin/sh -c "go run main.go"
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: docker/db/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: go_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - db-data:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306
        
volumes:
    db-data:
        driver: local